### ISSUE TITLE
0 accounts in database?

### ISSUE THREAD

**Issue by AdovinOFFICIAL** [nullworks/accgen-web#16]
Can't get any alts because it says there is 0 accounts in the database.

**Comment by buff1337** [comment]
same

**Comment by Ashesh3** [comment]
We are investigating the issue.

**Comment by Ashesh3** [comment]
Issue Resolved.

**Comment by BenCat07** [comment]
Issue resolved.

**Comment by TotallyNotElite** [comment]
Issue not fixed yet we're investigating...

**Comment by AdovinOFFICIAL** [comment]
Alright

**Comment by MarlinTheFish2** [comment]
can you please also check the released account creator? it doesn't work keeps throwing out UNKNOWN error.......

**Comment by AdovinOFFICIAL** [comment]
Make a seperate Issue for that

**Comment by TotallyNotElite** [comment]
Ok seems like our backend is being overloaded by more than 20 recaptcha approved requests for accounts per second. Might be bots. We're raising the recaptcha security level.

**Comment by Ashesh3** [comment]
> can you please also check the released account creator? it doesn't work keeps throwing out UNKNOWN error.......
> (unknwn in the application, in the gui it says something about ip banned from steam which is not true lmao...) i'm using the 2captcha with correct key etc..

That [project ](https://github.com/Ashesh3/Steam-Account-Generator)is no longer supported. No fixes will be made, you can always look at the source and fix it for yourself. Please don't post issues about that project here.

**Comment by MarlinTheFish2** [comment]
okk i was wondering because it said last update was 16 days ago i thought it would be still continued, no problem can you give us an eta on when the generator will be up back working? thanks

**Comment by BenCat07** [comment]
we don't know yet when it will be back up this might take a while

**Comment by buff1337** [comment]
fixed  btw

**Comment by buff1337** [comment]
Login: CharmingOceanicHippopotamus
Password: Bumpychain65
E-Mail address: charmingoceanichippopotamus@inboxkitten.com

**Comment by MarlinTheFish2** [comment]
it isn't working.. still showing 0, tried also shitf+f5... it gave me an account but not as fast as before, now it takes 30+ seconds??

**Comment by Ashesh3** [comment]
We are still working on a fix.

**Comment by TotallyNotElite** [comment]
It seems like we have successfully resolved the issue. We are now able to keep up with the huge rise in demand (we went from 5 accounts per minute to 30+ per minute).
